ユーザモデルを追加してログインなどの機能を実装する
wakatakeru/attendance_sheet_collector pull request #4
Opened 2018-04-10 11:22 UTC by wakatakeru

ユーザモデルを追加してログインの機能を実装した。
学籍番号とパスワードでのログインが可能である。
教授側のホームページと、受講生側のホームページの振分に対応している。
また、アクセスコントロールも有効化した。
E2Eテストを記述した。

## 確認してほしいこと

- データベースにseedのデータを挿入する
- Rspecによりテストを実施する
- viewの挙動を目視で確認する

2018-04-10 16:19 UTC, takuminish commented
sign upは実装していないかんじ??
実装していなければ、申し訳ないけどユーザアカウントをコンソールで作る方法を書いてほしいですー

2018-04-11 06:46 UTC, wakatakeru commented
sign upは実装していないです！
ユーザ登録は、管理者がWeb上で一括でできるような機能を開発する予定です。

2018-04-11 06:48 UTC, wakatakeru commented on app/assets/stylesheets/application.css
> +*= require devise_bootstrap_views
> Unknown word (CssSyntaxError)
> [link](https://sideci.com/gh/128867412/pull_requests/4)

SCSSのため

2018-04-11 06:50 UTC, wakatakeru commented on app/assets/stylesheets/application.css
> +*= require devise_bootstrap_views
> Unknown word (CssSyntaxError)
> [link](https://sideci.com/gh/128867412/pull_requests/4)

SCSSのため

2018-04-11 07:56 UTC, takuminish requested changes
application.html.erbでのページ遷移をlink_toに変更する点以外は、特に問題ないと思います。

2018-04-11 07:56 UTC, takuminish commented on app/views/layouts/application.html.erb
> +            <a class="nav-link" data-method="delete" href="/users/sign_out" rel="nofollow" data-toggle="tooltip" data-placement="bottom">
link_toを使った方がいいのではないでしょうかー

2018-04-11 08:10 UTC, wakatakeru commented on app/views/layouts/application.html.erb
> +            <a class="nav-link" data-method="delete" href="/users/sign_out" rel="nofollow" data-toggle="tooltip" data-placement="bottom">
あ！ホントですね！直しておきます〜！

2018-04-11 08:12 UTC, takuminish approved these changes

2018-04-11 08:13 UTC, merged